"""Add new table NewsExchange

Revision ID: 001cf9396536
Revises: d720c9a75544
Create Date: 2023-07-01 15:21:34.961237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001cf9396536'
down_revision = 'd720c9a75544'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_finance_newsexchange',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_finance_newsexchange')
    # ### end Alembic commands ###
