"""Init database

Revision ID: 6fe00e566c22
Revises: 
Create Date: 2023-06-12 21:29:06.331183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe00e566c22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_finance_exchange',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('sales', sa.Float(), nullable=False),
    sa.Column('buy', sa.Float(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('m_finance_exchange')
    # ### end Alembic commands ###
