"""Column Source Group

Revision ID: d720c9a75544
Revises: 6fe00e566c22
Create Date: 2023-07-01 12:05:06.026840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd720c9a75544'
down_revision = '6fe00e566c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m_finance_exchange', sa.Column('group_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m_finance_exchange', 'group_source')
    # ### end Alembic commands ###
